const data=window.GTS_DATA; const categories=[['accueil','Accueil'],['personnages','Personnages'],['concepts','Concepts'],['technologies','Technologies'],['institutions','Institutions'],['lieux','Lieux'],['objets','Objets']];
let state={category:'accueil',query:'',tag:'Tous'};
const $=s=>document.querySelector(s); const nav=$('#categoryNav'),grid=$('#cardGrid'),chips=$('#filterChips'),count=$('#resultCount'),empty=$('#emptyState'),home=$('#homeView');
function categoryCount(c){return c==='accueil'?data.length:data.filter(x=>x.category===c).length}
function renderNav(){nav.innerHTML=categories.map(([id,label])=>`<button class="nav-btn ${state.category===id?'active':''}" data-category="${id}"><span>${label}</span><small>${categoryCount(id)}</small></button>`).join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));}
function setCategory(c){state.category=c;state.tag='Tous';render();if(innerWidth<760)$('#sidebar').classList.remove('open')}
function visibleData(){let arr=state.category==='accueil'?data:data.filter(x=>x.category===state.category);const q=state.query.trim().toLowerCase();if(q)arr=arr.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(state.tag!=='Tous')arr=arr.filter(x=>x.tags.includes(state.tag));return arr}
function renderChips(base){const tags=['Tous',...new Set(base.flatMap(x=>x.tags))];chips.innerHTML=tags.map(t=>`<button class="chip ${state.tag===t?'active':''}" data-tag="${t}">${t}</button>`).join('');chips.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.tag=b.dataset.tag;renderCards()})}
function renderCards(){const base=state.category==='accueil'?data:data.filter(x=>x.category===state.category);renderChips(base);const arr=visibleData();count.textContent=`${arr.length} fiche${arr.length>1?'s':''}`;grid.innerHTML=arr.map(x=>`<article class="entry-card" data-id="${x.id}"><div class="card-meta">${x.type}</div><h3>${x.title}</h3><p>${x.summary}</p><div class="card-footer"><span class="tag">${x.tags[0]}</span><span>Ouvrir →</span></div></article>`).join('');empty.classList.toggle('hidden',arr.length>0);grid.querySelectorAll('[data-id]').forEach(c=>c.onclick=()=>openDetail(c.dataset.id))}
function render(){renderNav();home.classList.toggle('hidden',state.category!=='accueil'||!!state.query);const label=categories.find(x=>x[0]===state.category)?.[1]||'Canon';$('#viewEyebrow').textContent=state.query?'RECHERCHE':state.category==='accueil'?'SÉLECTION':'ARCHIVES';$('#viewTitle').textContent=state.query?`Résultats pour « ${state.query} »`:state.category==='accueil'?'Fiches essentielles':label;renderCards()}
function openDetail(id){const x=data.find(e=>e.id===id);if(!x)return;$('#modalContent').innerHTML=`<div class="detail-kicker">${x.type}</div><h2 class="detail-title" id="modalTitle">${x.title}</h2><p class="detail-summary">${x.subtitle} — ${x.summary}</p><div class="detail-grid">${Object.entries(x.facts).map(([k,v])=>`<div class="fact"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>${x.sections.map(s=>`<section class="detail-section"><h4>${s.title}</h4>${s.text?`<p>${s.text}</p>`:''}${s.items?`<ul>${s.items.map(i=>`<li>${i}</li>`).join('')}</ul>`:''}</section>`).join('')}`;$('#detailModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(){$('#detailModal').classList.add('hidden');document.body.style.overflow=''}
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});$('#searchInput').oninput=e=>{state.query=e.target.value;state.tag='Tous';render()};$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('gts-theme',document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem('gts-theme')==='light')document.documentElement.classList.add('light');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#randomBtn').onclick=()=>openDetail(data[Math.floor(Math.random()*data.length)].id);document.querySelectorAll('[data-open-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.openCategory));render();
