const data = window.GTS_DATA || [];
const categoryLabels = {personnages:'Personnages',concepts:'Concepts',technologies:'Technologies',institutions:'Institutions',lieux:'Lieux',objets:'Objets'};
const icons = {personnages:'◉',concepts:'◇',technologies:'⌬',institutions:'▣',lieux:'⌂',objets:'◆'};
const $ = s => document.querySelector(s);
const state = {view:'home', category:null, tag:'Tous', editor:false, favorites:new Set(JSON.parse(localStorage.getItem('gts-favorites')||'[]')), recent:JSON.parse(localStorage.getItem('gts-recent')||'[]')};

function savePrefs(){localStorage.setItem('gts-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('gts-recent',JSON.stringify(state.recent));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function counts(){return Object.keys(categoryLabels).map(id=>({id,label:categoryLabels[id],count:data.filter(x=>x.category===id).length}));}
function renderNav(){
  $('#categoryNav').innerHTML=`<button class="nav-btn ${state.view==='home'?'active':''}" data-view="home"><span>Accueil</span><small>${data.length}</small></button>`+
  counts().map(c=>`<button class="nav-btn ${state.category===c.id?'active':''}" data-category="${c.id}"><span>${icons[c.id]} ${c.label}</span><small>${c.count}</small></button>`).join('');
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
  document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));
  $('#favoriteCount').textContent=state.favorites.size;
}
function setView(view){state.view=view;state.category=null;render();closeSidebar();}
function setCategory(category){state.view='category';state.category=category;state.tag='Tous';render();closeSidebar();}
function closeSidebar(){if(innerWidth<820)$('#sidebar').classList.remove('open')}
function card(x,compact=false){return `<article class="entry-card ${compact?'compact':''}" data-id="${x.id}"><div class="card-top"><span class="type-pill">${x.type}</span><button class="favorite-mini ${state.favorites.has(x.id)?'active':''}" data-favorite="${x.id}" aria-label="Favori">${state.favorites.has(x.id)?'★':'☆'}</button></div><h3>${x.title}</h3><p>${x.summary}</p><div class="card-footer"><span>${x.tags?.[0]||'Canon'}</span><strong>Ouvrir →</strong></div></article>`}
function bindCards(){document.querySelectorAll('[data-id]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-favorite]'))return;openDetail(c.dataset.id)});document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.favorite)});}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);savePrefs();renderNav();render();toast(state.favorites.has(id)?'Ajouté aux favoris':'Retiré des favoris');}
function featured(){return {cover:data.find(x=>x.id.includes('anahita'))||data[0],district:data.find(x=>/olympia/i.test(x.title))||data.find(x=>x.category==='lieux'),tech:data.find(x=>x.category==='technologies'),institution:data.find(x=>x.category==='institutions')};}
function homeView(){const f=featured();return `<section class="hero"><div class="hero-copy"><p class="eyebrow">GTS CANON ENGINE · 2075</p><h1>Le savoir du monde<br><em>au-dessus du monde.</em></h1><p>Explorez les personnages, lieux, technologies et institutions qui composent le canon officiel de GTS.</p><div class="hero-actions"><button class="primary-btn" data-category="personnages">Explorer le canon</button><button class="secondary-btn" id="randomBtn">Fiche aléatoire</button></div></div><div class="hero-stat-card"><span>ÉTAT DU CANON</span><strong>${data.length}</strong><small>fiches disponibles dans A2</small><div class="stat-line"><span>${Object.keys(categoryLabels).length}</span><small>catégories actives</small></div><div class="stat-line"><span>≈ 5 000</span><small>Homo excelsior en 2075</small></div><div class="stat-line"><span>55</span><small>Districts Excelsior</small></div></div></section>
  <section class="dashboard"><div class="section-head"><div><p class="eyebrow">TABLEAU DE BORD</p><h2>À la une du canon</h2></div><span>Mise à jour · Sprint A2</span></div>
  <div class="feature-grid"><article class="feature-card feature-large" data-id="${f.cover.id}"><p class="eyebrow">COVER OF THE MONTH</p><h3>${f.cover.title}</h3><p>${f.cover.summary}</p><span>Découvrir la fiche →</span></article>${[f.district,f.tech,f.institution].filter(Boolean).map((x,i)=>`<article class="feature-card" data-id="${x.id}"><p class="eyebrow">${['DISTRICT À LA UNE','TECHNOLOGIE','INSTITUTION'][i]}</p><h3>${x.title}</h3><p>${x.summary}</p></article>`).join('')}</div>
  <div class="section-head spaced"><div><p class="eyebrow">EXPLORATION</p><h2>Fiches essentielles</h2></div><button class="text-btn" data-view="recent">Voir l’historique →</button></div><div class="card-grid">${data.slice(0,6).map(x=>card(x)).join('')}</div></section>`}
function categoryView(){const base=data.filter(x=>x.category===state.category);const tags=['Tous',...new Set(base.flatMap(x=>x.tags||[]))];const shown=state.tag==='Tous'?base:base.filter(x=>(x.tags||[]).includes(state.tag));return `<section class="page"><div class="page-title"><p class="eyebrow">ARCHIVES DU CANON</p><h1>${categoryLabels[state.category]}</h1><p>${shown.length} fiche${shown.length>1?'s':''} disponible${shown.length>1?'s':''}</p></div><div class="chip-row">${tags.map(t=>`<button class="chip ${state.tag===t?'active':''}" data-tag="${t}">${t}</button>`).join('')}</div><div class="card-grid">${shown.map(x=>card(x)).join('')}</div></section>`}
function listView(kind){const ids=kind==='favorites'?[...state.favorites]:state.recent;const entries=ids.map(id=>data.find(x=>x.id===id)).filter(Boolean);const title=kind==='favorites'?'Favoris':'Consultés récemment';return `<section class="page"><div class="page-title"><p class="eyebrow">BIBLIOTHÈQUE PERSONNELLE</p><h1>${title}</h1><p>${entries.length} fiche${entries.length>1?'s':''}</p></div>${entries.length?`<div class="card-grid">${entries.map(x=>card(x)).join('')}</div>`:`<div class="empty-state"><strong>Aucune fiche ici pour le moment.</strong><p>Ouvrez des fiches ou ajoutez-les à vos favoris.</p></div>`}</section>`}
function render(){renderNav();const view=$('#appView');view.innerHTML=state.view==='home'?homeView():state.view==='category'?categoryView():listView(state.view);document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{state.tag=b.dataset.tag;render()});$('#randomBtn')?.addEventListener('click',()=>openDetail(data[Math.floor(Math.random()*data.length)].id));bindCards();}
function relationIds(x){const text=JSON.stringify(x).toLowerCase();return data.filter(y=>y.id!==x.id && text.includes(y.title.toLowerCase().split(' ')[0])).slice(0,4);}
function openDetail(id){const x=data.find(e=>e.id===id);if(!x)return;state.recent=[id,...state.recent.filter(v=>v!==id)].slice(0,12);savePrefs();renderNav();const rel=relationIds(x);$('#modalContent').innerHTML=`<div class="detail-kicker">${x.type}</div><div class="detail-heading"><div><h2 class="detail-title" id="modalTitle">${x.title}</h2><p class="detail-summary">${x.subtitle||''}${x.subtitle?' — ':''}${x.summary}</p></div><button class="favorite-btn ${state.favorites.has(x.id)?'active':''}" data-favorite="${x.id}">${state.favorites.has(x.id)?'★ Favori':'☆ Ajouter aux favoris'}</button></div><div class="detail-grid">${Object.entries(x.facts||{}).map(([k,v])=>`<div class="fact"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div>${(x.sections||[]).map(s=>`<section class="detail-section"><h4>${s.title}</h4>${s.text?`<p>${s.text}</p>`:''}${s.items?`<ul>${s.items.map(i=>`<li>${i}</li>`).join('')}</ul>`:''}</section>`).join('')}${rel.length?`<section class="detail-section"><h4>Fiches liées</h4><div class="relation-grid">${rel.map(r=>`<button data-related="${r.id}"><span>${r.type}</span><strong>${r.title}</strong></button>`).join('')}</div></section>`:''}${state.editor?`<section class="editor-panel"><h4>Mode éditeur · données structurées</h4><pre>${escapeHtml(JSON.stringify(x,null,2))}</pre></section>`:''}`;$('#detailModal').classList.remove('hidden');document.body.style.overflow='hidden';$('#modalContent [data-favorite]')?.addEventListener('click',()=>{toggleFavorite(id);openDetail(id)});document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>openDetail(b.dataset.related));}
function escapeHtml(s){return s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function closeModal(){$('#detailModal').classList.add('hidden');document.body.style.overflow=''}
function openSearch(){const o=$('#searchOverlay');o.classList.remove('hidden');$('#searchInput').value='';renderSearch('');setTimeout(()=>$('#searchInput').focus(),20)}
function closeSearch(){$('#searchOverlay').classList.add('hidden')}
function renderSearch(q){const term=q.trim().toLowerCase();const results=(term?data.filter(x=>JSON.stringify(x).toLowerCase().includes(term)):data.slice(0,7)).slice(0,10);$('#searchResults').innerHTML=`<p class="search-caption">${term?'RÉSULTATS':'ACCÈS RAPIDE'}</p>${results.map(x=>`<button class="search-result" data-search-id="${x.id}"><span>${x.type}</span><strong>${x.title}</strong><small>${x.summary}</small></button>`).join('')||'<div class="empty-search">Aucun résultat.</div>'}`;document.querySelectorAll('[data-search-id]').forEach(b=>b.onclick=()=>{closeSearch();openDetail(b.dataset.searchId)});}

document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.querySelectorAll('[data-close-search]').forEach(x=>x.onclick=closeSearch);$('#searchLaunch').onclick=openSearch;$('#searchInput').oninput=e=>renderSearch(e.target.value);$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('gts-theme',document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem('gts-theme')==='light')document.documentElement.classList.add('light');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#editorBtn').onclick=()=>{state.editor=!state.editor;$('#editorBtn').classList.toggle('active',state.editor);toast(state.editor?'Mode éditeur activé':'Mode éditeur désactivé')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeSearch()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});render();
