const data=window.GTS_DATA||[]; const schema=window.GTS_SCHEMA||{required:[],recommended:[]};
const labels={personnages:'Personnages',concepts:'Concepts',technologies:'Technologies',institutions:'Institutions',lieux:'Lieux',objets:'Objets'};
const icons={personnages:'◉',concepts:'◇',technologies:'⌬',institutions:'▣',lieux:'⌂',objets:'◆'};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={view:'home',category:null,tag:'Tous',editor:false,favorites:new Set(JSON.parse(localStorage.getItem('gts-favorites')||'[]')),recent:JSON.parse(localStorage.getItem('gts-recent')||'[]')};
function save(){localStorage.setItem('gts-favorites',JSON.stringify([...state.favorites]));localStorage.setItem('gts-recent',JSON.stringify(state.recent))}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function setView(v){state.view=v;state.category=null;render();if(innerWidth<820)$('#sidebar').classList.remove('open')}
function setCategory(c){state.view='category';state.category=c;state.tag='Tous';render();if(innerWidth<820)$('#sidebar').classList.remove('open')}
function nav(){const special=['timeline','districts','studio','database','audit','favorites','recent'];$('#categoryNav').innerHTML=`<button class="nav-btn ${state.view==='home'?'active':''}" data-view="home"><span>Accueil</span><small>${data.length}</small></button>`+Object.keys(labels).map(c=>`<button class="nav-btn ${state.category===c?'active':''}" data-category="${c}"><span>${icons[c]} ${labels[c]}</span><small>${data.filter(x=>x.category===c).length}</small></button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',special.includes(b.dataset.view)&&state.view===b.dataset.view));$('#favoriteCount').textContent=state.favorites.size}
function card(x){return `<article class="entry-card" data-id="${x.id}"><div class="card-top"><span class="type-pill">${esc(x.type)}</span><button class="favorite-mini ${state.favorites.has(x.id)?'active':''}" data-favorite="${x.id}">${state.favorites.has(x.id)?'★':'☆'}</button></div><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><div class="card-footer"><span>${esc(x.tags?.[0]||'Canon')}</span><strong>Ouvrir →</strong></div></article>`}
function bind(){document.querySelectorAll('[data-id]').forEach(c=>c.onclick=e=>{if(!e.target.closest('[data-favorite]'))detail(c.dataset.id)});document.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();fav(b.dataset.favorite)});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>setCategory(b.dataset.category))}
function fav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();render();toast(state.favorites.has(id)?'Ajouté aux favoris':'Retiré des favoris')}
function home(){const a=data.find(x=>x.id==='anahita-rahimi'),o=data.find(x=>x.id==='olympia'),g=data.find(x=>x.id==='gts-therapy');return `<section class="hero"><div class="hero-copy"><p class="eyebrow">GTS CANON ENGINE · SPRINT C3</p><h1>Le canon devient<br><em>un outil de production.</em></h1><p>Explorez le lore, contrôlez sa cohérence et préparez les futurs articles de GTS Magazine depuis une même base.</p><div class="hero-actions"><button class="primary-btn" data-view="studio">Ouvrir le Studio</button><button class="secondary-btn" data-view="timeline">Voir la chronologie</button></div></div><div class="hero-stat-card"><span>KNOWLEDGE CORE</span><strong>${data.length}</strong><small>fiches structurées</small><div class="stat-line"><span>${data.reduce((n,x)=>n+(x.relations?.length||0),0)}</span><small>relations explicites</small></div><div class="stat-line"><span>${new Set(data.map(x=>x.year)).size}</span><small>jalons chronologiques</small></div><div class="stat-line"><span>${data.filter(x=>x.category==='lieux').length}</span><small>districts documentés</small></div></div></section><section class="dashboard"><div class="section-head"><div><p class="eyebrow">À LA UNE</p><h2>Canon éditorial</h2></div><span>Sprint C3 · Fiche intégrale Anahita</span></div><div class="feature-grid"><article class="feature-card feature-large" data-id="${a.id}"><p class="eyebrow">COVER OF THE MONTH</p><h3>${a.title}</h3><p>${a.summary}</p><span>Découvrir la fiche →</span></article><article class="feature-card" data-id="${o.id}"><p class="eyebrow">DISTRICT</p><h3>${o.title}</h3><p>${o.summary}</p></article><article class="feature-card" data-id="${g.id}"><p class="eyebrow">TECHNOLOGIE</p><h3>${g.title}</h3><p>${g.summary}</p></article></div><div class="section-head spaced"><div><p class="eyebrow">FONDATIONS</p><h2>Fiches essentielles</h2></div></div><div class="card-grid">${data.slice(0,8).map(card).join('')}</div></section>`}
function category(){const base=data.filter(x=>x.category===state.category),tags=['Tous',...new Set(base.flatMap(x=>x.tags||[]))],shown=state.tag==='Tous'?base:base.filter(x=>x.tags?.includes(state.tag));return `<section class="page"><div class="page-title"><p class="eyebrow">ARCHIVES DU CANON</p><h1>${labels[state.category]}</h1><p>${shown.length} fiches structurées</p></div><div class="chip-row">${tags.map(t=>`<button class="chip ${state.tag===t?'active':''}" data-tag="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="card-grid">${shown.map(card).join('')}</div></section>`}
function timeline(){return `<section class="page"><div class="page-title"><p class="eyebrow">2050 → 2075</p><h1>Chronologie</h1><p>Les principaux jalons disponibles dans le canon.</p></div><div class="timeline">${[...data].sort((a,b)=>a.year-b.year).map(x=>`<button class="timeline-item" data-id="${x.id}"><span>${x.year}</span><div><strong>${esc(x.title)}</strong><p>${esc(x.summary)}</p></div></button>`).join('')}</div></section>`}
function districts(){const d=data.filter(x=>x.category==='lieux');return `<section class="page"><div class="page-title"><p class="eyebrow">ATLAS EXCELSIOR</p><h1>Districts documentés</h1><p>Première vue géographique du réseau mondial.</p></div><div class="atlas-grid">${d.map(x=>`<article class="atlas-card" data-id="${x.id}"><span>${esc(x.facts?.Rang||'District')}</span><h3>${esc(x.title)}</h3><p>${esc(x.subtitle||'')}</p><small>${esc(x.tags?.join(' · '))}</small></article>`).join('')}</div></section>`}
function studio(){return `<section class="page"><div class="page-title"><p class="eyebrow">GTS MAGAZINE</p><h1>Studio éditorial</h1><p>Composez un brief d’article à partir des fiches du canon.</p></div><div class="studio-grid"><form class="studio-form" id="studioForm"><label>Type d’article<select id="articleType"><option>Portrait</option><option>Dossier</option><option>Interview</option><option>Technologie</option><option>District à la une</option></select></label><label>Sujet principal<select id="articleSubject">${data.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('')}</select></label><label>Angle éditorial<textarea id="articleAngle" placeholder="Ex. prestige, architecture, influence culturelle…"></textarea></label><label>Longueur<select id="articleLength"><option>2 pages</option><option>4 pages</option><option>6 pages</option><option>8 pages</option></select></label><button class="primary-btn" type="submit">Générer le brief</button></form><article class="brief-panel" id="briefPanel"><p class="eyebrow">BRIEF DE PRODUCTION</p><h3>Aucun brief généré</h3><p>Choisissez un sujet. Le système utilisera uniquement les données présentes dans le canon et signalera les informations manquantes.</p></article></div></section>`}
function completeness(x){const fields=[...schema.required,...schema.recommended],present=fields.filter(k=>{const v=x[k];return Array.isArray(v)?v.length>0:(v&&typeof v==='object')?Object.keys(v).length>0:Boolean(v)});return Math.round(present.length/fields.length*100)}
function database(){const canonical=data.filter(x=>x.status==='canon').length,drafts=data.filter(x=>x.status==='draft').length,fields=[...schema.required,...schema.recommended];return `<section class="page"><div class="page-title"><p class="eyebrow">CANON DATABASE · SCHEMA ${esc(schema.version)}</p><h1>Base de connaissances</h1><p>Vue structurée des identifiants, statuts, sources et champs nécessaires à la production éditoriale.</p></div><div class="database-stats"><article><strong>${data.length}</strong><span>fiches</span></article><article><strong>${canonical}</strong><span>canon validé</span></article><article><strong>${drafts}</strong><span>brouillons</span></article><article><strong>${data.reduce((n,x)=>n+(x.relations?.length||0),0)}</strong><span>relations</span></article></div><div class="schema-panel"><div><p class="eyebrow">CHAMPS OBLIGATOIRES</p>${schema.required.map(f=>`<code>${esc(f)}</code>`).join('')}</div><div><p class="eyebrow">CHAMPS RECOMMANDÉS</p>${schema.recommended.map(f=>`<code>${esc(f)}</code>`).join('')}</div></div><div class="database-table"><div class="database-row database-head"><span>ID canonique</span><span>Fiche</span><span>Statut</span><span>Source</span><span>Complétude</span></div>${data.map(x=>`<button class="database-row" data-id="${x.id}"><code>${esc(x.canonId)}</code><strong>${esc(x.title)}</strong><span class="status ${esc(x.status)}">${esc(x.status)}</span><span>${esc(x.source)}</span><span><b>${completeness(x)}%</b></span></button>`).join('')}</div></section>`}
function audit(){const rows=data.map(x=>{const miss=[];if(!x.year)miss.push('année');if(!x.facts||Object.keys(x.facts).length<2)miss.push('faits');if(!x.sections?.length)miss.push('contenu');if(!x.relations?.length)miss.push('relations');return {x,miss}});const ok=rows.filter(r=>!r.miss.length).length;return `<section class="page"><div class="page-title"><p class="eyebrow">QUALITÉ DES DONNÉES</p><h1>Audit du canon</h1><p>${ok}/${data.length} fiches satisfont les exigences minimales A4.</p></div><div class="audit-summary"><strong>${Math.round(ok/data.length*100)}%</strong><span>complétude minimale</span><button class="secondary-btn" id="exportBtn">Exporter le JSON</button></div><div class="audit-table">${rows.map(r=>`<button data-id="${r.x.id}"><strong>${esc(r.x.title)}</strong><span class="${r.miss.length?'warn':'ok'}">${r.miss.length?'Manque : '+r.miss.join(', '):'Complet'}</span></button>`).join('')}</div></section>`}
function list(kind){const ids=kind==='favorites'?[...state.favorites]:state.recent,items=ids.map(id=>data.find(x=>x.id===id)).filter(Boolean);return `<section class="page"><div class="page-title"><p class="eyebrow">BIBLIOTHÈQUE</p><h1>${kind==='favorites'?'Favoris':'Consultés récemment'}</h1><p>${items.length} fiches</p></div>${items.length?`<div class="card-grid">${items.map(card).join('')}</div>`:'<div class="empty-state"><strong>Aucune fiche ici.</strong></div>'}</section>`}
function render(){nav();const map={home,category,timeline,districts,studio,database,audit,favorites:()=>list('favorites'),recent:()=>list('recent')};$('#appView').innerHTML=(map[state.view]||home)();bind();document.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{state.tag=b.dataset.tag;render()});$('#studioForm')?.addEventListener('submit',e=>{e.preventDefault();makeBrief()});$('#exportBtn')?.addEventListener('click',exportJSON)}
function characterDetail(x,rel){
  const groups=Object.entries(x.profile||{}).map(([group,fields])=>`<section class="profile-group"><h4>${esc(group)}</h4><dl>${Object.entries(fields).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></section>`).join('');
  const toc=(x.sections||[]).map((section,index)=>`<a href="#character-section-${index}">${esc(section.title)}</a>`).join('');
  const highlights=(x.highlights||[]).map(h=>`<div class="character-highlight"><span>${esc(h.label)}</span><strong>${esc(h.value)}</strong></div>`).join('');
  const sections=(x.sections||[]).map((section,index)=>`<section class="character-copy-section" id="character-section-${index}"><p class="section-number">${String(index+1).padStart(2,'0')}</p><div><h3>${esc(section.title)}</h3>${section.text?`<p>${esc(section.text)}</p>`:''}${section.items?`<ul>${section.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:''}</div></section>`).join('');
  const timeline=(x.timeline||[]).map(item=>`<article class="personal-timeline-item"><time>${esc(item.year)}</time><div><h4>${esc(item.title)}</h4><p>${esc(item.text)}</p></div></article>`).join('');
  const gallery=(x.gallery||[]).map((item,index)=>`<article class="gallery-placeholder"><div><span>${String(index+1).padStart(2,'0')}</span><strong>AR</strong></div><h4>${esc(item.title)}</h4><p>${esc(item.caption)}</p></article>`).join('');
  return `<article class="character-master-entry">
    <header class="character-hero">
      <div class="character-portrait"><span>${esc(x.portrait?.initials||'GTS')}</span><small>${esc(x.portrait?.caption||'Illustration canonique')}</small></div>
      <div class="character-hero-copy"><p class="detail-kicker">MASTER ENTRY · ${esc(x.canonId)}</p><h2>${esc(x.title)}</h2><p class="character-subtitle">${esc(x.subtitle||'')}</p><blockquote>“${esc(x.quotes?.[0]||'')}”</blockquote><div class="character-badges"><span>🇮🇷 Iran</span><span>Homo excelsior</span><span>Génération II</span><span>18 mètres</span><span class="status ${esc(x.status)}">${esc(x.status)}</span></div></div>
      <button class="favorite-btn character-favorite" data-favorite="${x.id}">${state.favorites.has(x.id)?'★ Favori':'☆ Ajouter aux favoris'}</button>
    </header>
    <section class="character-highlights">${highlights}</section>
    <div class="character-layout">
      <aside class="character-sidebar"><div class="character-sidebar-title"><span>PROFIL OFFICIEL</span><strong>2075</strong></div>${groups}<section class="character-meta"><h4>Métadonnées</h4><p><span>Statut</span><b>${esc(x.status)}</b></p><p><span>Source</span><b>${esc(x.source)}</b></p><p><span>Mise à jour</span><b>${esc(x.updated)}</b></p><p><span>Complétude</span><b>${completeness(x)}%</b></p><p><span>Gabarit</span><b>${esc(x.template||'standard')}</b></p><p><span>Version de fiche</span><b>${esc(x.version||'1.0')}</b></p><p><span>Couverture canon</span><b>${esc(x.completion||'Non renseignée')}</b></p></section></aside>
      <main class="character-content"><nav class="character-toc"><span>Sommaire</span>${toc}</nav>${sections}
        <section class="character-special-section"><div class="special-heading"><p class="eyebrow">PARCOURS</p><h3>Chronologie personnelle</h3></div><div class="personal-timeline">${timeline}</div></section>
        <section class="character-special-section"><div class="special-heading"><p class="eyebrow">ARCHIVES VISUELLES</p><h3>Galerie</h3><p>Les emplacements sont prêts à recevoir les illustrations officielles sans casser la mise en page.</p></div><div class="character-gallery">${gallery}</div></section>
        <section class="character-special-section"><div class="special-heading"><p class="eyebrow">KNOWLEDGE GRAPH</p><h3>Relations canoniques</h3></div><div class="relation-grid character-relations">${rel.map(r=>`<button data-related="${r.id}"><span>${esc(r.type)}</span><strong>${esc(r.title)}</strong><small>${esc(r.summary)}</small></button>`).join('')||'<p>Aucune relation renseignée.</p>'}</div></section>
        ${x.visual?`<section class="character-special-section visual-spec"><h3>Spécification visuelle</h3><p><strong>Sujet :</strong> ${esc(x.visual.subject||'Non défini')}</p><p><strong>Obligatoire :</strong> ${esc((x.visual.required||[]).join(' · ')||'Non défini')}</p><p><strong>Interdit :</strong> ${esc((x.visual.forbidden||[]).join(' · ')||'Non défini')}</p></section>`:''}
      </main>
    </div>
  </article>`;
}
function genericDetail(x,rel){return `<div class="detail-kicker">${esc(x.type)} · ${esc(x.canonId)}</div><div class="detail-heading"><div><h2 class="detail-title">${esc(x.title)}</h2><p class="detail-summary">${esc(x.subtitle?x.subtitle+' — ':'')}${esc(x.summary)}</p></div><button class="favorite-btn" data-favorite="${x.id}">${state.favorites.has(x.id)?'★ Favori':'☆ Ajouter aux favoris'}</button></div><div class="canon-meta"><span class="status ${esc(x.status)}">${esc(x.status)}</span><span>Source : ${esc(x.source)}</span><span>Mis à jour : ${esc(x.updated)}</span><span>Complétude : ${completeness(x)}%</span></div><div class="detail-grid">${Object.entries(x.facts||{}).map(([k,v])=>`<div class="fact"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div>${(x.sections||[]).map(s=>`<section class="detail-section"><h4>${esc(s.title)}</h4>${s.text?`<p>${esc(s.text)}</p>`:''}${s.items?`<ul>${s.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul>`:''}</section>`).join('')}${x.aliases?.length?`<section class="detail-section"><h4>Alias et appellations</h4><div class="chip-row">${x.aliases.map(a=>`<span class="chip">${esc(a)}</span>`).join('')}</div></section>`:''}${x.visual?`<section class="detail-section visual-spec"><h4>Spécification visuelle</h4><p><strong>Sujet :</strong> ${esc(x.visual.subject||'Non défini')}</p><p><strong>Obligatoire :</strong> ${esc((x.visual.required||[]).join(' · ')||'Non défini')}</p><p><strong>Interdit :</strong> ${esc((x.visual.forbidden||[]).join(' · ')||'Non défini')}</p></section>`:''}<section class="detail-section"><h4>Graphe de relations</h4><div class="relation-grid">${rel.map(r=>`<button data-related="${r.id}"><span>${esc(r.type)}</span><strong>${esc(r.title)}</strong></button>`).join('')||'<p>Aucune relation renseignée.</p>'}</div></section>${state.editor?`<section class="editor-panel"><h4>Données structurées</h4><pre>${esc(JSON.stringify(x,null,2))}</pre></section>`:''}`}
function detail(id){const x=data.find(v=>v.id===id);if(!x)return;state.recent=[id,...state.recent.filter(v=>v!==id)].slice(0,12);save();const rel=(x.relations||[]).map(id=>data.find(v=>v.id===id)).filter(Boolean);const isMasterCharacter=x.category==='personnages'&&String(x.template||'').startsWith('personnage-geante-v');$('#modalContent').innerHTML=isMasterCharacter?characterDetail(x,rel):genericDetail(x,rel);$('#detailModal').classList.remove('hidden');$('#detailModal').classList.toggle('character-modal',isMasterCharacter);document.body.style.overflow='hidden';$('#modalContent [data-favorite]').onclick=()=>{fav(id);detail(id)};document.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>detail(b.dataset.related))}

function makeBrief(){const x=data.find(v=>v.id===$('#articleSubject').value),type=$('#articleType').value,len=$('#articleLength').value,angle=$('#articleAngle').value.trim();const missing=[];if(!x.sections?.length)missing.push('développement narratif');if(!x.facts||Object.keys(x.facts).length<3)missing.push('données factuelles complémentaires');const related=(x.relations||[]).map(id=>data.find(v=>v.id===id)?.title).filter(Boolean);$('#briefPanel').innerHTML=`<p class="eyebrow">BRIEF DE PRODUCTION</p><h3>${esc(type)} · ${esc(x.title)}</h3><p><strong>Format :</strong> ${esc(len)}</p><p><strong>Angle :</strong> ${esc(angle||'Présentation générale fidèle au canon')}</p><h4>Structure proposée</h4><ol><li>Ouverture : ${esc(x.summary)}</li><li>Contexte et données clés</li><li>Développement à partir des sections de la fiche</li><li>Encadré relations : ${esc(related.join(', ')||'aucune relation')}</li><li>Conclusion et portée dans l’univers GTS</li></ol><h4>Images à produire</h4><ul><li>Visuel principal réaliste du sujet</li><li>Vue contextuelle liée à ${esc(related[0]||'son environnement')}</li><li>Détail éditorial ou infographie</li></ul><div class="brief-status ${missing.length?'warn':'ok'}">${missing.length?'À compléter dans la base : '+missing.join(', '):'Données suffisantes pour une première rédaction.'}</div>`}
function exportJSON(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gts-canon-a4.json';a.click();URL.revokeObjectURL(a.href);toast('Export JSON créé')}
function search(q){const t=q.trim().toLowerCase(),r=(t?data.filter(x=>JSON.stringify(x).toLowerCase().includes(t)):data.slice(0,8)).slice(0,12);$('#searchResults').innerHTML=`<p class="search-caption">${t?'RÉSULTATS':'ACCÈS RAPIDE'}</p>${r.map(x=>`<button class="search-result" data-search-id="${x.id}"><span>${esc(x.type)}</span><strong>${esc(x.title)}</strong><small>${esc(x.summary)}</small></button>`).join('')||'<div class="empty-search">Aucun résultat.</div>'}`;document.querySelectorAll('[data-search-id]').forEach(b=>b.onclick=()=>{closeSearch();detail(b.dataset.searchId)})}
function openSearch(){$('#searchOverlay').classList.remove('hidden');$('#searchInput').value='';search('');setTimeout(()=>$('#searchInput').focus(),20)} function closeSearch(){$('#searchOverlay').classList.add('hidden')} function closeModal(){$('#detailModal').classList.add('hidden');document.body.style.overflow=''}
document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.querySelectorAll('[data-close-search]').forEach(x=>x.onclick=closeSearch);$('#searchLaunch').onclick=openSearch;$('#searchInput').oninput=e=>search(e.target.value);$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('gts-theme',document.documentElement.classList.contains('light')?'light':'dark')};if(localStorage.getItem('gts-theme')==='light')document.documentElement.classList.add('light');$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#editorBtn').onclick=()=>{state.editor=!state.editor;$('#editorBtn').classList.toggle('active',state.editor);toast(state.editor?'Mode éditeur activé':'Mode éditeur désactivé')};document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeSearch()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});render();

// Sprint B2 — Personnages fondateurs
